# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90c9054089dc8ce7f91e3d50de45fed4e4705727fc89c20c500d5035688a27a2a8fae02f9148e72804b71ce48086e2ee0008473086d4aad52178d5615b544d3c

test:
  secret_key_base: 0f1d96555f0468bd44cdecc104e17417605054a0b755acd6674c69f6c7065c326de9a5ce2a6fdfe8674dbe9e1f8cb2672134abce89b7b4e9bff83fefb5deb31e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
